name: 'Futureself'
services:
  futureself-backend:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: futureself-api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env.api.local
    ports:
      - 5010:5001
  
  futureself-web:
    build: 
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: futureself-web
    restart: unless-stopped
    env_file:
      - ./apps/web/.env
    ports:
      - 8010:5173