name: 'Futureself backend'
services:
  future-self-backend:
    image: ghcr.io/ibsule/futureself:latest
    container_name: futureself-backend-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5010:5001